[section#func.wrap.badcall
    [:en] Class [`bad_function_call]
    [:zh_CN] 类 [`bad_function_call]
[:][%@library bad_function_call]
]

[para]
[:en]
An exception of type [`bad_function_call] is thrown by [`function::operator()]
([#func.wrap.func.inv]) when the function wrapper object has no target.
[:zh_CN]
当函数包装器对象没有目标时，[`function::operator()]（[#func.wrap.func.inv]）抛出
[`bad_function_call] 类型的异常。

[codeblock:synopsis]
namespace std {
  class bad_function_call : public exception {
  public:
    // [:en] see [#exception] for the specification of the special member functions
    // [|:zh_CN] 有关特殊成员函数的说明，参见 [#exception]
    const char* what() const noexcept override;
  };
}
[codeblock:end]

[%@library bad_function_call[!what]]
[%@library what[!bad_function_call]]
[enter:description]
[para:returns]
[:en] An [%@impldef return value of [`bad_function_call::what()]] [$:sc ntbs].
[:zh_CN] 一个[%@impldef [`bad_function_call::what()] 的返回值]由实现定义的
[$:sc ntbs]。
[exit:description]
